---
# Create docker directory for nginx
- name: Create docker directory for nginx
  file: path="{{ playbook_dir }}/docker/nginx" state=directory
  tags:
    - configuration
- name: Create Nginx Dockerfile
  template: src="nginx-dockerfile.j2" dest="{{ playbook_dir }}/docker/nginx/Dockerfile"
  tags:
    - configuration
- name: Copy extra files for Nginx image
  copy: src="{{ item }}" dest="{{ playbook_dir }}/docker/nginx/{{ item }}"
  with_items:
    - "confd-watch"
    - "nginx.conf.tmpl"
    - "nginx.toml"
  tags:
    - configuration
- name: Build Nginx image
  docker_image: docker_url="tcp://{{ registry_hostname }}":2375 path="{{ playbook_dir }}/docker/nginx" name="{{ nginx_image_name }}" state="build"
  tags:
    - docker
    - docker_build
- name: Push Nginx image to repo
  shell: "docker -H tcp://{{ registry_hostname }}:2375 push {{ nginx_image_name }}"
  tags:
    - docker
    - docker_push

# Create units for nginx
- name: Create Nginx units
  template: src="nginx@x.service.j2" dest="{{ playbook_dir }}/units/nginx@{{ item }}.service"
  with_items: 
    - "80"
  tags:
    - fleet
    - fleet_start
- name: Submit Nginx units
  shell: "fleetctl --tunnel {{ fleet_endpoint }} submit {{ playbook_dir }}units/nginx@{{ item }}.service"
  with_items:
    - "80"
  tags:
    - configuration
- name: Start Nginx units
  shell: "fleetctl --tunnel {{ fleet_endpoint }} start {{ playbook_dir }}untis/nginx@{{ item }}.service"
  with_items:
    - "80"
  tags:
    - fleet
    - fleet_start
  
